name: 'Validate json files'
description: 'Check the validity of json files'
author: 'Raa Labs AS'
inputs:
  directory:
    description: "A directory of files to include in the json validation, defaults to root directory"
    default: "." # 
    required: false
runs:
  using: 'docker'
  image: 'docker://raalabs/validate-json:v0.0.6'
