name: Build Docker Image

on:
  push:
    branches:
      - '**'
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      shell: bash
      run: |
        docker build -f Dockerfile -t testbuild .
